### ISSUE TITLE
resolveAsRelativePath is incorrect

### ISSUE THREAD

**Issue by yunxing** [reasonml/dependency-env#4]
From the code here: https://github.com/npm-ml/dependency-env/blob/773f63f5ebf26fd1ad9011c00371ae6833cd4943/.bin/dependencyEnv.js#L87
it looks like when the flag is set, it is actually resolving as _absolute_ path.

**Comment by jordwalke** [comment]
```
node
> require('path').resolve('/x/y', './blah')
'/x/y/blah'
```

This seems to work as intended?

**Comment by jordwalke** [comment]
I think the terminology of "resolve as relative path" might just be confusing. It's resolving the _value_ as a relative path, _into_ an absolute path.

**Comment by yunxing** [comment]
@jordwalke Now I understand. Interesting, nothing important.
