### ISSUE TITLE
generate makefile output

### ISSUE THREAD

**Issue by yunxing** [reasonml/dependency-env#6]
The current output of dependency-env only work with bash compatible syntax. In environments where we don't have bash such as Makefile, we need to generate output that works with `make`.

**Comment by jordwalke** [comment]
why closed? Seems like a good idea?

**Comment by yunxing** [comment]
oh I merged it as a standalone command

**Comment by yunxing** [comment]
https://github.com/reasonml/dependency-env/blob/master/bashExportsToMake

**Comment by jordwalke** [comment]
Great!
